---
title: "Beta Disper"
author: "MD"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
 html_document:
    toc: true
    toc_float: true
editor_options: 
  chunk_output_type: console
---


```{r, include=FALSE}
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(message = FALSE)
library(tidyverse)
library(egg)
library(ggthemes)
library(SciViews)
library(dunn.test)
library(MASS)
library(RColorBrewer)
library(car)
library(emmeans)
library(multcomp)
library(multcompView)
library(devtools)
library(dplyr)
library(ggplot2)
library(metacoder)
library(MicEco)
library(phyloseq)
library(reticulate)
library(readxl)
library(vegan)
library(knitr)
library(agricolae)
```

# Read in Data

```{r, echo=FALSE}
source("myFunctions.R")
P.rel <- readRDS('data/P.rel.RDS')

```

```{r run model}
d <- data.frame(sample_data(P.rel))
data <- data.frame(t(otu_table(P.rel)))
data <- decostand(data, method='hellinger') # using hellinger's transformation
dist <- vegdist(data, method='bray')


```

# Beta dispersion

## Model

```{r}
mod <- betadisper(dist, interaction(d$Week, d$Fert), type = c("centroid"),bias.adjust = F)
mod
par(mfrow=c(1,1))
plot(mod)
anova(mod)
```

## Basic plots

```{r}
plot(mod, ellipse = TRUE, hull = FALSE, conf = 0.90) # 90% data ellipse
(mod.HSD <- TukeyHSD(mod))
plot(mod.HSD)
boxplot(mod,
        xlab="Week")
print(mod, digits = max(3, getOption("digits") - 3),
                           neigen = 8)
x <- rep(c(1,2,3,4,5,6,7,8),each=20)
df <- as.data.frame(mod$distances)
df$name <- rownames(df)
```

## Model

```{r}
df<- read.csv('data/betadisper.csv')
df$week <- as.factor(df$week)
mod <- lm(data=df, log(int.dist) ~ Fert*week)
par(mfrow=c(2,2))
plot(mod)
aov.mod<- aov(mod)
summary(aov.mod)
t<-HSD.test(mod, "week");t
res <- emmeans(mod, list(pairwise ~ week*Fert), adjust = "fdr")
res
plot(res[[1]], horizontal=F)
groups <- data.frame(multcomp::cld(res[[1]], adjust='fdr', Letters=c("abcdefghijklmnopqrstuvwxy"), decreasing=F))
groups <- groups %>%
  arrange(week, Fert)
```

## Boxplot

```{r warning=F}
p <- ggplot() +
  geom_boxplot(data=df, aes(x=week, y=log(int.dist),fill=Fert)) +
  labs(y="Log-Transformed Distance to the Centroid", x="Week")+
  theme_classic()+
  scale_fill_manual(values = c('#1F78B4', '#33A02C', '#E31A1C', '#FF7F00'),
                    labels=c('Control', 'ESN', 'High Urea', 'Low Urea')) +
  theme(axis.text.x=element_text(colour = "black"), 
        axis.text.y=element_text(colour = "black"),
        axis.title=element_text(face="bold"),
        legend.title = element_blank(),
        axis.line = element_line(colour = "black"))+
  # geom_text(label='AB', x=1,y=-1.2, size = 5) +
  # geom_text(label='AB', x=2,y=-1.1, size = 5) +
  # geom_text(label='A', x=3,y=-1.1, size = 5) +
  # geom_text(label='AB', x=4,y=-0.7, size = 5) +
  # geom_text(label='BC', x=5,y=-1.1, size = 5) +
  # geom_text(label='CD', x=6,y=-1.6, size = 5) +
  # geom_text(label='CD', x=7,y=-1.4, size = 5) +
  # geom_text(label='D', x=8,y=-1.6, size = 5)+
  # geom_segment(aes(x = 0.65, y = -1.23, xend = 1.36, yend = -1.23), lwd=0.4)+
  # geom_segment(aes(x = 1.65, y = -1.13, xend = 2.36, yend = -1.13), lwd=0.4)+
  # geom_segment(aes(x = 2.65, y = -1.13, xend = 3.36, yend = -1.13), lwd=0.4)+
  # geom_segment(aes(x = 3.65, y = -0.73, xend = 4.36, yend = -0.73), lwd=0.4)+
  # geom_segment(aes(x = 4.65, y = -1.13, xend = 5.36, yend = -1.13), lwd=0.4)+
  # geom_segment(aes(x = 5.65, y = -1.63, xend = 6.36, yend = -1.63), lwd=0.4)+
  # geom_segment(aes(x = 6.65, y = -1.43, xend = 7.36, yend = -1.43), lwd=0.4)+
  # geom_segment(aes(x = 7.65, y = -1.63, xend = 8.36, yend = -1.63), lwd=0.4)+
  geom_text(data=groups,stat='identity',
            aes(x=week, y=emmean+SE, label=.group), 
            size=4,position=position_dodge(.9));p
ggsave(plot=p, filename = 'output/Fig5betadisper.png',width = 10,height = 6);p

```

