---
title: "dbRDA"
author: "MD"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
 html_document:
   toc: true
   toc_float: true
 editor_options:
   chunck_output_type: console
   chunk_output_type: console
---

```{r setup, include=FALSE}
library(vegan)
library(pairwiseAdonis)
library(RColorBrewer)

```
# Read in data

```{r read in data}
P.rel <- readRDS('data/P.rel.RDS')

```


# Run model
```{r run model}
d <- data.frame(sample_data(P.rel))

data <- data.frame(t(otu_table(P.rel)))
data <- decostand(data, method='hellinger')

dist <- vegdist(data, method='bray')

ord <- capscale(dist ~ Week*Fert, data=d)
pair.mod<-pairwise.adonis(dist,factors=d$Week, p.adjust.m = "fdr")
pa<-pair.mod %>% filter(.,p.adjusted<0.05)

adonis2(dist ~  Week*Fert, data=d, perm=999)
# adonis2(formula = dist ~ Week * Fert, data = d, permutations = 999)
#            Df SumOfSqs      R2       F Pr(>F)    
# Week        1   1.1252 0.16257 27.6804  0.001 ***
# Fert        3   0.1604 0.02318  1.3154  0.120    
# Week:Fert   3   0.1072 0.01548  0.8787  0.611    
# Residual  136   5.5286 0.79877                   
# Total     143   6.9214 1.00000   
pairwise.adonis(dist,factors=d$Week, p.adjust.m = "fdr")

```

# Ordinations

## dbrda Plot
```{r ordination}

ev <- eigenvals(ord)
Axis1_exp = round(ev[1] / sum(ev) * 100, 1)
Axis2_exp = round(ev[2] / sum(ev) * 100, 1)

axes <- as.data.frame(vegan::scores(ord, display="sites", choices=c(1:2)))
names(axes) <- c("Axis1", "Axis2")
axes <- cbind(d, axes)
axes$Week <- as.character(axes$Week)

p<-ggplot(data=axes, aes(x=Axis1, y=Axis2, fill=Week, shape=Fert)) +
  geom_point(size=6,color='black') +
  stat_ellipse(aes(group= Week, color= Week), type='t', level=0.95) +
  scale_fill_manual(values = rev(brewer.pal(8, "Paired")))+
  scale_colour_manual(values = rev(brewer.pal(8, "Paired")))+
  scale_shape_manual(values=c(21,22,23,24), labels=c('Control', 'ESN', 'High Urea', 'Low Urea')) +
  guides(fill = guide_legend(
    override.aes=list(shape = rep(21)))) +
  labs(x=paste0('CAP1 (', Axis1_exp, '%)'), 
       y=paste0('CAP2 (', Axis2_exp, '%)'),
       alpha='none') +
  theme_classic();p
#ggsave(plot=p, filename = 'output/Fig3dbRDA.png',width = 12,height = 6)
```

## Biplot
```{r}

d <- data.frame(sample_data(P.rel))

data <- data.frame(t(otu_table(P.rel)))
names(data) <- tax_table(P.rel)[,'species']
data <- sqrt(data) 

dist <- vegdist(data, method='bray')
```


```{r}
# run PCoA for different treatment groups
#ord <- capscale(dist ~ Fert * Rate * Soil, data=d)
# 
# mod0 <- capscale(dist ~ 1, data=d)
# mod1 <- capscale(dist ~ Fert*Week, data=d)
# mod <- ordistep(mod0, scope=formula(mod1), direction='both')
# mod
# mod$anova

ord <- capscale(dist ~ Week*Fert, data=d)

sppscores(ord) <- data
biplot <- data.frame(vegan::scores(ord, display='species'))
biplot <- biplot[abs(biplot$CAP1) > 0.3 | abs(biplot$CAP2) > 0.3, ]

adonis2(dist ~ Fert*Week, data=d, perm=999, by="terms")

### get eigenvalues and proportion explained
ev <- eigenvals(ord)
Axis1_exp = round(ev[1] / sum(ev) * 100, 1)
Axis2_exp = round(ev[2] / sum(ev) * 100, 1)

### get PC axes
axes <- as.data.frame(vegan::scores(ord, display="sites", choices=c(1:2)))
names(axes) <- c("Axis1", "Axis2")
axes <- cbind(d, axes) 

axes$Week <- as.factor(axes$Week)

```



# Fig 1 Complete Data set

```{r pcoa fig 1A non facet, fig.width=11, fig.height=6, fig.cap="PCoA fig 1A, Complete Data Set. Using species and Bray-Curtis distance."}
biplot$letters <- c('B',"C","A")

p<-ggplot(data=axes, aes(x=Axis1, y=Axis2, fill=Week, shape=Fert)) +
  geom_point(size=6) +
  stat_ellipse(aes(group= Week, color= Week), type='t', level=0.95) +
  scale_fill_brewer(palette = 'Paired') +
  scale_shape_manual(values=c(21,22,23,24)) +
  guides(fill = guide_legend(
    override.aes=list(shape = rep(21,)))) +
  labs(x=paste0('CAP1 (', Axis1_exp, '%)'), 
       y=paste0('CAP2 (', Axis2_exp, '%)')) +
  scale_color_brewer(palette = 'Paired') +
  geom_segment(data=biplot, inherit.aes=F, aes(x=0, xend=CAP1, y=0, yend=CAP2), arrow=arrow(length=unit(0.25, 'cm'))) +
  geom_text(data=biplot, show.legend=F,inherit.aes=F, size=6,aes(
    x=CAP1, y=0.2+CAP2, label=letters, 
    family = 'mono', fontface = 'bold.italic'))+
     theme_classic();p
  # geom_text(label="A",size=6, x=1,y=2.5,aes(family = 'mono', fontface = 'bold.italic'))+
  # geom_text(label="B",size=6, x=1,y=2.2,aes(family = 'mono', fontface = 'bold.italic'))+
  # geom_text(label="C",size=6, x=1,y=1.9,aes(family = 'mono', fontface = 'bold.italic'))+
  # geom_text(label="D",size=6, x=1,y=1.6,aes(family = 'mono', fontface = 'bold.italic'))+
  # geom_text(label="E",size=6, x=1,y=1.3,aes(family = 'mono', fontface = 'bold.italic'))

ggsave(plot=p, filename = 'figures/rdabiplot.png',width = 10,height = 10)
#label=row.names(biplot)
```

# Unconstrained pcoa
```{r}


sample_data(P.rel)$week <- as.factor(sample_data(P.rel)$Week)


GloPa.pcoa = ordinate(P.rel, method="PCoA", distance=dist)
plot_scree(GloPa.pcoa, "Scree plot for Global Patterns, UniFrac/PCoA")
p <- plot_ordination(P.rel, GloPa.pcoa, "samples", color="week") + 
  geom_point(size=5) + scale_colour_hue(guide = FALSE) +
  scale_color_brewer(palette = 'Paired')+
  stat_ellipse(aes(group= week, color= week), type='t', level=0.95) +
  theme_classic();p
ggsave(plot=p, filename = 'figures/PCoA.png',width = 12,height = 8)

```

