---
title: "Weekly Differential Abundance"
author: "MD"
date: "'r format(Sys.time(), '%b %d, %Y')'"
output: 
 html_document:
   toc: true
   toc_float: true
 editor_options:
   chunck_output_type: console
   chunk_output_type: console
---

```{r}
library(microbiomeMarker)
library(tidyverse)
library(readr)
library(egg)
library(phyloseq)
library(readxl)
```


```{r, differential abundance prep}
P.count <- readRDS('data/P.count.RDS')


P.c <- subset_samples(P.count, Fert=='Control')
P.u <- subset_samples(P.count, Fert=='Urea')
P.hu <- subset_samples(P.count, Fert=='HUrea')
P.e <- subset_samples(P.count, Fert=='ESN')


colnames(tax_table(P.c)) <- c('Kingdom', 'Phylum', 'Class', 'Order', 'Family', 'Genus', 'Species')
colnames(tax_table(P.u)) <- c('Kingdom', 'Phylum', 'Class', 'Order', 'Family', 'Genus', 'Species')
colnames(tax_table(P.hu)) <- c('Kingdom', 'Phylum', 'Class', 'Order', 'Family', 'Genus', 'Species')
colnames(tax_table(P.e)) <- c('Kingdom', 'Phylum', 'Class', 'Order', 'Family', 'Genus', 'Species')
```


# Calculate the weekly changes 

## Control
```{r, diff abund Control}
#weeks 1v2
out.glom <- microbiomeMarker::run_deseq2(
  P.c, group="Week",taxa_rank="Species",norm="RLE",transform="identity",
  p_adjust='fdr', pvalue_cutoff=0.05,
  contrast=c('1','2'))
out <-data.frame(microbiomeMarker::marker_table(out.glom)) %>% 
  mutate(Week='1v2') %>% 
  mutate(Fert='Control')
out$enrich_group <- gsub('X','',out$enrich_group)
write.csv(out, 'data/DA.files/DA_CK_1v2.csv', row.names = FALSE)

#weeks 2v3
out.glom <- microbiomeMarker::run_deseq2(
  P.c, group="Week",taxa_rank="Species",norm="RLE",transform="identity",
  p_adjust='fdr', pvalue_cutoff=0.05,
  contrast=c('2','3'))
out <-data.frame(microbiomeMarker::marker_table(out.glom))%>% 
  mutate(Week='2v3') %>% 
  mutate(Fert='Control')
out$enrich_group <- gsub('X','',out$enrich_group)
write.csv(out, 'data/DA.files/DA_CK_2v3.csv', row.names = FALSE)

#weeks 3v4
out.glom <- microbiomeMarker::run_deseq2(
  P.c, group="Week",taxa_rank="Species",norm="RLE",transform="identity",
  p_adjust='fdr', pvalue_cutoff=0.05,
  contrast=c('3','4'))
out <-data.frame(microbiomeMarker::marker_table(out.glom))%>% 
  mutate(Week='3v4') %>% 
  mutate(Fert='Control')
out$enrich_group <- gsub('X','',out$enrich_group)
write.csv(out, 'data/DA.files/DA_CK_3v4.csv', row.names = FALSE)

#weeks 4v5
out.glom <- microbiomeMarker::run_deseq2(
  P.c, group="Week",taxa_rank="Species",norm="RLE",transform="identity",
  p_adjust='fdr', pvalue_cutoff=0.05,
  contrast=c('4','5'))
out <-data.frame(microbiomeMarker::marker_table(out.glom))%>% 
  mutate(Week='4v5') %>% 
  mutate(Fert='Control')
out$enrich_group <- gsub('X','',out$enrich_group)
write.csv(out, 'data/DA.files/DA_CK_4v5.csv', row.names = FALSE)

#weeks 5v6
out.glom <- microbiomeMarker::run_deseq2(
  P.c, group="Week",taxa_rank="Species",norm="RLE",transform="identity",
  p_adjust='fdr', pvalue_cutoff=0.05,
  contrast=c('5','6'))
out <-data.frame(microbiomeMarker::marker_table(out.glom))%>% 
  mutate(Week='5v6') %>% 
  mutate(Fert='Control')
out$enrich_group <- gsub('X','',out$enrich_group)
write.csv(out, 'data/DA.files/DA_CK_5v6.csv', row.names = FALSE)

#weeks 6v7
out.glom <- microbiomeMarker::run_deseq2(
  P.c, group="Week",taxa_rank="Species",norm="RLE",transform="identity",
  p_adjust='fdr', pvalue_cutoff=0.05,
  contrast=c('6','7'))
out <-data.frame(microbiomeMarker::marker_table(out.glom))%>% 
  mutate(Week='6v7') %>% 
  mutate(Fert='Control')
out$enrich_group <- gsub('X','',out$enrich_group)


#weeks 7v8
out.glom <- microbiomeMarker::run_deseq2(
  P.c, group="Week",taxa_rank="Species",norm="RLE",transform="identity",
  p_adjust='fdr', pvalue_cutoff=0.05,
  contrast=c('7','8'))
out <-data.frame(microbiomeMarker::marker_table(out.glom))%>% 
  mutate(Week='7v8') %>% 
  mutate(Fert='Control')
out$enrich_group <- gsub('X','',out$enrich_group)
write.csv(out, 'data/DA.files/DA_CK_7v8.csv', row.names = FALSE)
```

## Low Urea
```{r, diff abund low Urea}
#weeks 1v2
out.glom <- microbiomeMarker::run_deseq2(
  P.u, group="Week",taxa_rank="Species",norm="RLE",transform="identity",
  p_adjust='fdr', pvalue_cutoff=0.05,
  contrast=c('1','2'))
out <-data.frame(microbiomeMarker::marker_table(out.glom))%>% 
  mutate(Week='1v2') %>% 
  mutate(Fert='Low_Urea')
out$enrich_group <- gsub('X','',out$enrich_group)
write.csv(out, 'data/DA.files/DA_LU_1v2.csv', row.names = FALSE)

#weeks 2v3
out.glom <- microbiomeMarker::run_deseq2(
  P.u, group="Week",taxa_rank="Species",norm="RLE",transform="identity",
  p_adjust='fdr', pvalue_cutoff=0.05,
  contrast=c('2','3'))
out <-data.frame(microbiomeMarker::marker_table(out.glom))%>% 
  mutate(Week='2v3') %>% 
  mutate(Fert='Low_Urea')
out$enrich_group <- gsub('X','',out$enrich_group)
write.csv(out, 'data/DA.files/DA_LU_2v3.csv', row.names = FALSE)

#weeks 3v4
out.glom <- microbiomeMarker::run_deseq2(
  P.u, group="Week",taxa_rank="Species",norm="RLE",transform="identity",
  p_adjust='fdr', pvalue_cutoff=0.05,
  contrast=c('3','4'))
out <-data.frame(microbiomeMarker::marker_table(out.glom))%>% 
  mutate(Week='3v4') %>% 
  mutate(Fert='Low_Urea')
out$enrich_group <- gsub('X','',out$enrich_group)
write.csv(out, 'data/DA.files/DA_LU_3v4.csv', row.names = FALSE)

#weeks 4v5
out.glom <- microbiomeMarker::run_deseq2(
  P.u, group="Week",taxa_rank="Species",norm="RLE",transform="identity",
  p_adjust='fdr', pvalue_cutoff=0.05,
  contrast=c('4','5'))
out <-data.frame(microbiomeMarker::marker_table(out.glom))%>% 
  mutate(Week='4v5') %>% 
  mutate(Fert='Low_Urea')
out$enrich_group <- gsub('X','',out$enrich_group)
write.csv(out, 'data/DA.files/DA_LU_4v5.csv', row.names = FALSE)

#weeks 5v6
out.glom <- microbiomeMarker::run_deseq2(
  P.u, group="Week",taxa_rank="Species",norm="RLE",transform="identity",
  p_adjust='fdr', pvalue_cutoff=0.05,
  contrast=c('5','6'))
out <-data.frame(microbiomeMarker::marker_table(out.glom))%>% 
  mutate(Week='5v6') %>% 
  mutate(Fert='Low_Urea')
out$enrich_group <- gsub('X','',out$enrich_group)
write.csv(out, 'data/DA.files/DA_LU_5v6.csv', row.names = FALSE)

#weeks 6v7
out.glom <- microbiomeMarker::run_deseq2(
  P.u, group="Week",taxa_rank="Species",norm="RLE",transform="identity",
  p_adjust='fdr', pvalue_cutoff=0.05,
  contrast=c('6','7'))
out<-data.frame(microbiomeMarker::marker_table(out.glom))%>% 
  mutate(Week='6v7') %>% 
  mutate(Fert='Low_Urea')
out$enrich_group <- gsub('X','',out$enrich_group)
write.csv(out, 'data/DA.files/DA_LU_6v7.csv', row.names = FALSE)

#weeks 7v8
out.glom <- microbiomeMarker::run_deseq2(
  P.u, group="Week",taxa_rank="Species",norm="RLE",transform="identity",
  p_adjust='fdr', pvalue_cutoff=0.05,
  contrast=c('7','8'))
out <-data.frame(microbiomeMarker::marker_table(out.glom))%>% 
  mutate(Week='7v8') %>% 
  mutate(Fert='Low_Urea')
out$enrich_group <- gsub('X','',out$enrich_group)
write.csv(out, 'data/DA.files/DA_LU_7v8.csv', row.names = FALSE)
```


## High Urea
```{r, diff abund H Urea}
#weeks 1v2
out.glom <- microbiomeMarker::run_deseq2(
  P.hu, group="Week",taxa_rank="Species",norm="RLE",transform="identity",
  p_adjust='fdr', pvalue_cutoff=0.05,
  contrast=c('1','2'))
out <-data.frame(microbiomeMarker::marker_table(out.glom))%>% 
  mutate(Week='1v2') %>% 
  mutate(Fert='High_Urea')
out$enrich_group <- gsub('X','',out$enrich_group)
write.csv(out, 'data/DA.files/DA_HU_1v2.csv', row.names = FALSE)

#weeks 2v3
out.glom <- microbiomeMarker::run_deseq2(
  P.hu, group="Week",taxa_rank="Species",norm="RLE",transform="identity",
  p_adjust='fdr', pvalue_cutoff=0.05,
  contrast=c('2','3'))
out <-data.frame(microbiomeMarker::marker_table(out.glom))%>% 
  mutate(Week='2v3') %>% 
  mutate(Fert='High_Urea')
out$enrich_group <- gsub('X','',out$enrich_group)
write.csv(out, 'data/DA.files/DA_HU_2v3.csv', row.names = FALSE)

#weeks 3v4
out.glom <- microbiomeMarker::run_deseq2(
  P.hu, group="Week",taxa_rank="Species",norm="RLE",transform="identity",
  p_adjust='fdr', pvalue_cutoff=0.05,
  contrast=c('3','4'))
out<-data.frame(microbiomeMarker::marker_table(out.glom))%>% 
  mutate(Week='3v4') %>% 
  mutate(Fert='High_Urea')
out$enrich_group <- gsub('X','',out$enrich_group)
write.csv(out, 'data/DA.files/DA_HU_3v4.csv', row.names = FALSE)

#weeks 4v5
out.glom <- microbiomeMarker::run_deseq2(
  P.hu, group="Week",taxa_rank="Species",norm="RLE",transform="identity",
  p_adjust='fdr', pvalue_cutoff=0.05,
  contrast=c('4','5'))
out <-data.frame(microbiomeMarker::marker_table(out.glom))%>% 
  mutate(Week='4v5') %>% 
  mutate(Fert='High_Urea')
out$enrich_group <- gsub('X','',out$enrich_group)
write.csv(out, 'data/DA.files/DA_HU_4v5.csv', row.names = FALSE)

#weeks 5v6
out.glom <- microbiomeMarker::run_deseq2(
  P.hu, group="Week",taxa_rank="Species",norm="RLE",transform="identity",
  p_adjust='fdr', pvalue_cutoff=0.05,
  contrast=c('5','6'))
out <-data.frame(microbiomeMarker::marker_table(out.glom))%>% 
  mutate(Week='5v6') %>% 
  mutate(Fert='High_Urea')
out$enrich_group <- gsub('X','',out$enrich_group)
write.csv(out, 'data/DA.files/DA_HU_5v6.csv', row.names = FALSE)

#weeks 6v7
out.glom <- microbiomeMarker::run_deseq2(
  P.hu, group="Week",taxa_rank="Species",norm="RLE",transform="identity",
  p_adjust='fdr', pvalue_cutoff=0.05,
  contrast=c('6','7'))
out <-data.frame(microbiomeMarker::marker_table(out.glom))%>% 
  mutate(Week='6v7') %>% 
  mutate(Fert='High_Urea')
out$enrich_group <- gsub('X','',out$enrich_group)


#weeks 7v8
out.glom <- microbiomeMarker::run_deseq2(
  P.hu, group="Week",taxa_rank="Species",norm="RLE",transform="identity",
  p_adjust='fdr', pvalue_cutoff=0.05,
  contrast=c('7','8'))
out <-data.frame(microbiomeMarker::marker_table(out.glom))%>% 
  mutate(Week='7v8') %>% 
  mutate(Fert='High_Urea')
out$enrich_group <- gsub('X','',out$enrich_group)
write.csv(out, 'data/DA.files/DA_HU_7v8.csv', row.names = FALSE)
```

## ESN
```{r, diff abund ESN}
#weeks 1v2
out.glom <- microbiomeMarker::run_deseq2(
  P.e, group="Week",taxa_rank="Species",norm="RLE",transform="identity",
  p_adjust='fdr', pvalue_cutoff=0.05,
  contrast=c('1','2'))
out <-data.frame(microbiomeMarker::marker_table(out.glom))%>% 
  mutate(Week='1v2') %>% 
  mutate(Fert='ESN')
out$enrich_group <- gsub('X','',out$enrich_group)
write.csv(out, 'data/DA.files/DA_ESN_1v2.csv', row.names = FALSE)

#weeks 2v3
out.glom <- microbiomeMarker::run_deseq2(
  P.e, group="Week",taxa_rank="Species",norm="RLE",transform="identity",
  p_adjust='fdr', pvalue_cutoff=0.05,
  contrast=c('2','3'))
out <-data.frame(microbiomeMarker::marker_table(out.glom))%>% 
  mutate(Week='2v3') %>% 
  mutate(Fert='ESN')
out$enrich_group <- gsub('X','',out$enrich_group)
write.csv(out, 'data/DA.files/DA_ESN_2v3.csv', row.names = FALSE)

#3weeks 3v4
out.glom <- microbiomeMarker::run_deseq2(
  P.e, group="Week",taxa_rank="Species",norm="RLE",transform="identity",
  p_adjust='fdr', pvalue_cutoff=0.05,
  contrast=c('3','4'))
out <-data.frame(microbiomeMarker::marker_table(out.glom))%>% 
  mutate(Week='3v4') %>% 
  mutate(Fert='ESN')
out$enrich_group <- gsub('X','',out$enrich_group)
write.csv(out, 'data/DA.files/DA_ESN_3v4.csv', row.names = FALSE)

#weeks 4v5
out.glom <- microbiomeMarker::run_deseq2(
  P.e, group="Week",taxa_rank="Species",norm="RLE",transform="identity",
  p_adjust='fdr', pvalue_cutoff=0.05,
  contrast=c('4','5'))
out <-data.frame(microbiomeMarker::marker_table(out.glom))%>% 
  mutate(Week='4v5') %>% 
  mutate(Fert='ESN')
out$enrich_group <- gsub('X','',out$enrich_group)
write.csv(out, 'data/DA.files/DA_ESN_4v5.csv', row.names = FALSE)

#weeks 5v6
out.glom <- microbiomeMarker::run_deseq2(
  P.e, group="Week",taxa_rank="Species",norm="RLE",transform="identity",
  p_adjust='fdr', pvalue_cutoff=0.05,
  contrast=c('5','6'))
out <-data.frame(microbiomeMarker::marker_table(out.glom))%>% 
  mutate(Week='5v6') %>% 
  mutate(Fert='ESN')
out$enrich_group <- gsub('X','',out$enrich_group)
write.csv(out, 'data/DA.files/DA_ESN_5v6.csv', row.names = FALSE)

#weeks 6v7
out.glom <- microbiomeMarker::run_deseq2(
  P.e, group="Week",taxa_rank="Species",norm="RLE",transform="identity",
  p_adjust='fdr', pvalue_cutoff=0.05,
  contrast=c('6','7'))
out <-data.frame(microbiomeMarker::marker_table(out.glom))%>% 
  mutate(Week=' 6v7') %>% 
  mutate(Fert='ESN')
out$enrich_group <- gsub('X','',out$enrich_group)
write.csv(out, 'data/DA.files/DA_ESN_6v7.csv', row.names = FALSE)

#weeks 7v8
out.glom <- microbiomeMarker::run_deseq2(
  P.e, group="Week",taxa_rank="Species",norm="RLE",transform="identity",
  p_adjust='fdr', pvalue_cutoff=0.05,
  contrast=c('7','8'))
out <-data.frame(microbiomeMarker::marker_table(out.glom))%>% 
  mutate(Week='7v8') %>% 
  mutate(Fert='ESN')
out$enrich_group <- gsub('X','',out$enrich_group)
write.csv(out, 'data/DA.files/DA_ESN_7v8.csv', row.names = FALSE)
```

## Combine above into one df

```{r}
d <- list.files(path="data/DA.files", full.names = TRUE) %>% 
  lapply(read_csv) %>% 
  bind_rows 
d$enrich_group = as.factor(d$enrich_group)
write.csv(d, 'data/DA_all.csv')
```

## diff abund figure by week
```{r,  fig 1}
x = tapply(d$ef_logFC, d$feature, function(x) max(x))
x = sort(-x, TRUE)


p<-ggplot() + 
  geom_point(d, alpha=0.4,mapping=aes(
    x=Week, y=ef_logFC,   fill=enrich_group),size=5,color='black',pch=21) + 
  geom_hline(yintercept = 0)+
  facet_wrap(~Fert, ncol=4, scales='free')+
  scale_fill_brewer(palette = 'Set1')+
  labs(y='Log Fold Change')+
  theme(axis.text.x = element_text(vjust = 0.5),
        axis.text=element_text(size=10, colour = "black"), 
        axis.title=element_text(size=15,face="bold"),
        axis.line = element_line(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        panel.background = element_blank(),
        legend.key = element_blank(),
        legend.text = element_text(size = 14),
        legend.title = element_blank(),
        axis.title.x = element_blank(),
        strip.background = element_blank());p 
p<- tag_facet(p, size = 5);p #A=CK, B=ESN, C=HU, D=LU
ggsave(plot=p, filename = 'figures/DA-fert-byweek.png',width = 10,height = 8)
```

## diff abund early late volcano plot
```{r}

colnames(tax_table(P.count)) <- c('Kingdom', 'Phylum', 'Class', 'Order', 'Family', 'Genus', 'Species')


out.glom <- microbiomeMarker::run_deseq2(
  P.count, 
  group="Stage",
  taxa_rank="Species",
  norm="RLE",
  transform="identity",
  p_adjust='fdr', 
  pvalue_cutoff=1)

df<-data.frame(microbiomeMarker::marker_table(out.glom))
write.csv(df,"data/DA_early-late.csv")


df$sig <- ifelse(df$padj>0.05, "NS",
                                       ifelse(df$padj==0.05, "NS",
                                              ifelse(df$padj<0.05, "sig",NA)))
df$sig.stage <- paste(df$enrich_group,df$sig)


df$colors <- ifelse(df$sig=="NS", "NS",
                        ifelse(df$sig.stage=='Early sig',"Early",
                               ifelse(df$sig.stage=='Late sig','Late',NA)))
df<- arrange(df, -log(padj))

p<-ggplot(data=df)+
  geom_point(alpha=0.85,mapping= aes(
    fill=colors, x=ef_logFC,y=-log(padj)),
    size=5,color='black',pch=21) +
  scale_fill_manual(values = c('cornflowerblue','firebrick4','gray50'))+
  theme_classic()+
  labs(y=expression("-log"["10"] ~ "p" ["adj"]), 
       x=expression("log"["2"]~"Fold Change"))+
  theme(axis.text=element_text(size=10, colour = "black"), 
        axis.line = element_line(colour = "black"),
        legend.title = element_blank());p
ggsave(plot=p, filename = 'figures/DA-Volcano-early-late.png',width = 8,height = 8)

```

# DA functions by week

```{r}
kegg <- read_excel('data/EMU_database.GIBBs.KO.PICRUST2.xlsx', sheet='EMU_database.GIBBs.PICRUSt2', range='B9:BE17565') %>%
  mutate_if(is.numeric, replace_na, replace=0)

d.list <- d$feature
keggsub <- filter(kegg, Species %in% d.list)
names(d)[names(d) == 'feature'] <- 'Species'
d.kegg <- left_join(d,keggsub, by = 'Species') %>% 
filter(!NSTI=='NA')

d<- pivot_longer(d.kegg, cols=hcnA:nosZ, names_to = 'Gene', values_to = 'value') %>%   filter(!value==0)

d$Function <- ifelse(d$Gene=="hcnA", "Biocontrol",
                        ifelse(d$Gene=="budA","Biocontrol",
                               ifelse(d$Gene=="budC","Biocontrol",
                                      ifelse(d$Gene=="E3.2.1.6","Biocontrol",                                             ifelse(d$Gene=="E3.2.1.14","Biocontrol",                                                    ifelse(d$Gene=="phlD","Biocontrol",                                                       ifelse(d$Gene=="ituA","Biocontrol",  
                      ifelse(d$Gene=="fenA", "Biocontrol",
                        ifelse(d$Gene=="srfAA","Biocontrol",
                               ifelse(d$Gene=="rifM","Biocontrol",
                                      ifelse(d$Gene=="phzE","Biocontrol",
                                             ifelse(d$Gene=="ipdC","Stress",                                                    ifelse(d$Gene=="acdS","Stress",                                                           ifelse(d$Gene=="mbtI","Siderophore",                                                    ifelse(d$Gene=="entA", "Siderophore",
        ifelse(d$Gene=="pchB","Siderophore",
           ifelse(d$Gene=="bglX","C decomposition",
              ifelse(d$Gene=="bglB","C decomposition",
                 ifelse(d$Gene=="E3.2.1.21","C decomposition",                                          ifelse(d$Gene=="amiE","N decomposition",    
ifelse(d$Gene=="ureC","N decomposition",                                                    ifelse(d$Gene=="pqqC", "PO4 solubility",
        ifelse(d$Gene=="phoA","P decomposition",
           ifelse(d$Gene=="phoD","P decomposition",
              ifelse(d$Gene=="PHO","P decomposition",
                 ifelse(d$Gene=="appA","P decomposition",                                          ifelse(d$Gene=="phoN","P decomposition",                             ifelse(d$Gene=="aslA","S decomposition",                                                    ifelse(d$Gene=="nifH", "N-fixation",
        ifelse(d$Gene=="nifD","N-fixation",
           ifelse(d$Gene=="nifK","N-fixation",
              ifelse(d$Gene=="pmoA-amoA","Nitrification",
                 ifelse(d$Gene=="hao","Nitrification",                                          ifelse(d$Gene=="nirB","Dissimilatory nitrate reduction",    
ifelse(d$Gene=="nirD","Dissimilatory nitrate reduction",                                   ifelse(d$Gene=="nrfA", "Dissimilatory nitrate reduction",
        ifelse(d$Gene=="nirA","Assimilatory nitrate reduction",
           ifelse(d$Gene=="NIT-6","Assimilatory nitrate reduction",
              ifelse(d$Gene=="narG","Denitrification",
                 ifelse(d$Gene=="narH","Denitrification",                                          ifelse(d$Gene=="nirK","Denitrification",    
 ifelse(d$Gene=="nirS","Denitrification",                                   ifelse(d$Gene=="norB", "Denitrification",
        ifelse(d$Gene=="norC","Denitrification",
          ifelse(d$Gene=='nosZ','Denitrification',NA)))))))))))))))))))))))))))))))))))))))))))))

d<-d %>% dplyr::select(Species, enrich_group, Week, ef_logFC, padj, Fert, Gene, Function)
d<- arrange(d, Function)

level_order <- factor(d$Function, levels=c("Assimilatory nitrate reduction", 
                                           "Denitrification",
                                           "Dissimilatory nitrate reduction",
                                           "N-fixation",
                                           "N decomposition",
                                           "Nitrification",
                                           "P decomposition",
                                           "PO4 solubility",
                                           "Siderophore",
                                           "Biocontrol",
                                           "Stress",
                                           "S decomposition",
                                           "C decomposition"))
p<-ggplot(data=d)+
  geom_point(position=position_jitter(0.9),alpha=0.9,mapping= aes(
    fill=level_order, x=ef_logFC,y=-log(padj)),
    size=4,color='black',pch=21) +
  scale_fill_manual(values = c('gray90','gray50','gray20','springgreen4', 'lawngreen','darkolivegreen', 'blue','cornflowerblue','darkblue', 'red', 'firebrick','yellow2','goldenrod4'))+
  theme_classic()+
  facet_wrap(~Week, ncol = 2, scales='free')+
  labs(y=expression("-log"["10"] ~ "p" ["adj"]), 
       x=expression("log"["2"]~"Fold Change"))+
  theme(axis.text=element_text(size=10, colour = "black"), 
        axis.line = element_line(colour = "black"),
        legend.title = element_blank());p
ggsave(p, filename='figures/DA-functions-byweek.png', width=20, height=10)
```

